---
- name: Patch Linux servers
  hosts: all
  become: true

  tasks:
    - name: Update all installed packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Check if reboot is required
      ansible.builtin.command: needs-restarting -r
      register: reboot_check
      changed_when: false
      failed_when: reboot_check.rc not in [0, 1]

    - name: Reboot server if required
      ansible.builtin.reboot:
        reboot_timeout: 600
      when: reboot_check.rc == 1

    - name: Display current kernel
      ansible.builtin.command: uname -r
      register: kernel_version
      changed_when: false

    - name: Show current kernel
      ansible.builtin.debug:
        msg: "Current kernel is {{ kernel_version.stdout }}"
